/* Generated by npm run build. Edit src/ files. */
(() => {
'use strict';
// data/company.js
const company = {
  name: 'Fly Telecom Fibra', phone: '(81) 2011-3396', phoneRaw: '+558120113396', whatsapp: '558120113396',
  street: 'Rua Coronel Estevam Câmara, 337', district: 'Centro', city: 'Gravatá', state: 'PE',
  address: 'Rua Coronel Estevam Câmara, 337, Centro, Gravatá — PE',
  domain: 'https://flytelecomfibra.com.br',
  referral: { discount: '50%', text: 'Indique um amigo que contrate a Fly e ganhe 50% de desconto em uma mensalidade.', terms: 'O desconto é exclusivo para quem indica, após o pagamento da primeira mensalidade do indicado. O setor financeiro entra em contato em até 30 dias. Aplicável a uma mensalidade que não esteja em aberto ou em atraso. Sem limite de indicações.' },
  installation: 'Consulte o prazo de instalação para o seu endereço.',
  residentialTerms: 'Contratação sujeita à cobertura e à viabilidade técnica. Confirme valores, fidelidade, equipamentos e condições com nossa equipe antes de contratar.',
  meshTerms: 'Segundo ponto com taxa adicional, sujeito à análise de contratação e viabilidade técnica. Equipamentos em comodato.',
  // TODO comercial: reconciliar prazos de instalação (24h/48h) e publicar documentos jurídicos oficiais.
};


// data/links.js
const links = {
  central: 'https://flytelecom.sgp.tsmx.com.br/accounts/central/login',
  instagram: 'https://www.instagram.com/fly.telecomfibra/',
  apple: 'https://apps.apple.com/br/app/fly-telecom/id6758914646',
  google: 'https://play.google.com/store/apps/details?id=flytel.app.quark.flytelecom',
  speedtest: 'https://www.speedtest.net/pt', connection: 'https://www.minhaconexao.com.br/', nperf: 'https://www.nperf.com/pt/',
  original: company.domain,
};
const whatsapp = (message = 'Olá! Vim pelo site da Fly Telecom Fibra e gostaria de atendimento.') => `https://wa.me/${company.whatsapp}?text=${encodeURIComponent(message)}`;


// data/plans.js
const plans = [
  { id: 'essencial', name: 'Fly Essencial', speed: '300', unit: 'Mega', price: 69.90, wifi: 'Wi-Fi Básico', home: false, streaming: 'Watch + Zapping', support: 'Atendimento local', benefits: ['Wi-Fi Básico', 'Stream filmes e séries', 'Atendimento local'], caption: 'Para o seu dia a dia.' },
  { id: 'familia', name: 'Fly Família', speed: '500', unit: 'Mega', price: 74.90, wifi: 'Wi-Fi Premium', home: true, streaming: 'Watch + Zapping', support: 'Atendimento local', benefits: ['Wi-Fi Premium', 'Casa Conectada', 'Stream filmes e séries'], caption: 'Mais conexão para compartilhar.' },
  { id: 'premium', name: 'Fly Premium', speed: '700', unit: 'Mega', price: 79.90, wifi: 'Wi-Fi Premium', home: true, streaming: 'Watch + Zapping', support: 'Atendimento prioritário', benefits: ['Wi-Fi Premium + Casa Conectada', 'Stream filmes e séries', 'Atendimento prioritário'], caption: 'Para viver todas as possibilidades.', featured: true },
  { id: 'black', name: 'Fly Black', speed: '1', unit: 'Giga', price: 119.90, wifi: 'Wi-Fi Black', home: true, streaming: 'Watch + Zapping', support: 'Suporte em até 1 hora', benefits: ['Wi-Fi Black + Casa Conectada', 'Stream filmes e séries', 'Suporte em até 1 hora', 'Instalação prioritária'], caption: 'Sua conexão em outro nível.' },
];
const money = value => value.toLocaleString('pt-BR', { minimumFractionDigits: 2, maximumFractionDigits: 2 });
const planLink = plan => whatsapp(`Olá! Vim pelo site da Fly Telecom Fibra e gostaria de saber sobre o plano ${plan.name} de ${plan.speed} ${plan.unit}.`);
function recommendPlan({people, usage, devices}) {
  if (!['1–2', '3–4', '5+'].includes(people) || !['Streaming', 'Jogos', 'Home office', 'Redes sociais', 'Tudo isso'].includes(usage) || !['Até 5', '6–10', '10+'].includes(devices)) return null;
  if (people === '5+' && devices === '10+' && usage === 'Tudo isso') return plans[3];
  if (people === '5+' || devices === '10+' || usage === 'Tudo isso') return plans[2];
  if (people === '3–4' || devices === '6–10' || ['Jogos', 'Home office'].includes(usage)) return plans[1];
  return plans[0];
}


// data/faq.js
const faq = [
  ['Qual plano escolher?', 'Considere as pessoas, os dispositivos e os usos simultâneos da sua casa. Nosso seletor oferece uma sugestão inicial; a equipe Fly pode ajudar a confirmar a escolha.'],
  ['O que é download e upload?', 'Download é receber dados, como assistir a um vídeo. Upload é enviar dados, como compartilhar arquivos ou participar de uma videochamada. Consulte as velocidades de cada modalidade na contratação.'],
  ['Quanto tempo demora a instalação?', company.installation],
  ['Existe taxa de instalação?', 'O site oficial informa instalação gratuita nos planos residenciais e equipamento em comodato. Confirme as condições para o seu endereço. Pontos adicionais de Wi-Fi têm condições próprias.'],
  ['Como solicitar a segunda via?', 'Acesse a Central do Assinante ou o aplicativo Fly Telecom com seus dados de acesso para consultar as faturas. Se precisar, fale com nossa equipe.'],
  ['Como falar com o suporte?', `Você pode usar o WhatsApp, o aplicativo ou ligar para ${company.phone}. O atendimento é local, com uma equipe que conhece Gravatá.`],
  ['Como melhorar o Wi-Fi em outros cômodos?', `A Casa Conectada combina posicionamento estratégico e soluções Wi-Fi 6 e Mesh, conforme disponibilidade. ${company.meshTerms}`],
  ['É possível mudar o plano?', 'Fale com o atendimento para solicitar uma análise de mudança e conhecer as condições do plano desejado.'],
  ['Posso transferir para outro endereço?', 'A transferência depende da cobertura no novo endereço. Entre em contato com antecedência para confirmar viabilidade, agendamento e condições.'],
];
const connectionSteps = [
  { title: 'Confira cabos e energia', text: 'Veja se o roteador está ligado e se os cabos estão bem encaixados. Não desconecte nem dobre o cabo de fibra óptica.' },
  { title: 'Reinicie o equipamento', text: 'Desligue o roteador da tomada, aguarde 30 segundos e ligue novamente. Não pressione o botão Reset: ele pode apagar as configurações.' },
  { title: 'Aguarde alguns minutos', text: 'Espere o equipamento iniciar e as luzes estabilizarem antes de tentar conectar novamente.' },
  { title: 'Teste sua conexão', text: 'Abra um site e tente conectar outro dispositivo. Se apenas um aparelho não conecta, confira o Wi-Fi dele.' },
  { title: 'Vamos resolver juntos', text: 'Ainda sem conexão? Fale com o suporte Fly e informe quais verificações você já fez.' },
];


// coverage.js
function validateAddress({cep, street, number}) {
  if (!/^\d{5}-?\d{3}$/.test(cep.trim())) return 'Informe um CEP válido com 8 números.';
  if (street.trim().length < 3 || street.trim().length > 150) return 'Informe o nome da rua (entre 3 e 150 caracteres).';
  if (!number.trim() || number.trim().length > 20) return 'Informe o número ou S/N.';
  return '';
}
// Adaptador: substituir por integração real de cobertura quando disponibilizada.
function coverageLink(address) {
  const error = validateAddress(address);
  if (error) throw new Error(error);
  return whatsapp(`Olá! Gostaria de consultar disponibilidade da Fly para:\nCEP: ${address.cep.trim()}\nRua: ${address.street.trim()}\nNúmero: ${address.number.trim()}`);
}


// app.js
const $ = selector => document.querySelector(selector);
const header = $('#header');
const menuButton = $('.menu-toggle');
const nav = $('#navigation');
function closeMenu(returnFocus = false) {
  menuButton.setAttribute('aria-expanded', 'false');
  menuButton.setAttribute('aria-label', 'Abrir menu');
  nav.classList.remove('open');
  if (returnFocus) menuButton.focus();
}
menuButton.addEventListener('click', () => {
  const isOpen = menuButton.getAttribute('aria-expanded') !== 'true';
  menuButton.setAttribute('aria-expanded', String(isOpen));
  menuButton.setAttribute('aria-label', isOpen ? 'Fechar menu' : 'Abrir menu');
  nav.classList.toggle('open', isOpen);
});
nav.addEventListener('click', event => { if (event.target.closest('a')) closeMenu(); });
document.addEventListener('keydown', event => { if (event.key === 'Escape' && nav.classList.contains('open')) closeMenu(true); });
document.addEventListener('click', event => { if (!header.contains(event.target)) closeMenu(); });
matchMedia('(min-width: 1241px)').addEventListener('change', event => { if (event.matches) closeMenu(); });
let scheduled = false;
const updateHeader = () => { header.classList.toggle('scrolled', window.scrollY > 35); scheduled = false; };
window.addEventListener('scroll', () => { if (!scheduled) { scheduled = true; requestAnimationFrame(updateHeader); } }, { passive: true });
updateHeader();
const motion = matchMedia('(prefers-reduced-motion: reduce)');
if (!motion.matches && 'IntersectionObserver' in window) {
  const observer = new IntersectionObserver(entries => entries.forEach(entry => {
    if (entry.isIntersecting) { entry.target.classList.add('visible'); observer.unobserve(entry.target); }
  }), { threshold: 0.06 });
  document.querySelectorAll('.reveal').forEach(node => observer.observe(node));
  document.documentElement.classList.add('js-motion');
  // Ensure in-page navigation reveals the destination immediately.
  const revealAnchor = () => {
    let id;
    try { id = decodeURIComponent(location.hash.slice(1)); } catch { return; }
    const target = document.getElementById(id);
    if (!target) return;
    target.closest('.reveal')?.classList.add('visible');
    target.querySelectorAll('.reveal').forEach(node => node.classList.add('visible'));
  };
  window.addEventListener('hashchange', revealAnchor);
  revealAnchor();
}
let lastDialogTrigger;
function openDialog(dialog, trigger) {
  lastDialogTrigger = trigger;
  dialog.showModal();
  document.body.style.overflow = 'hidden';
  dialog.querySelector('.close-dialog').focus();
}
document.querySelectorAll('dialog').forEach(dialog => {
  dialog.querySelector('.close-dialog').addEventListener('click', () => dialog.close());
  dialog.addEventListener('click', event => {
    const rect = dialog.getBoundingClientRect();
    if (event.target === dialog && (event.clientX < rect.left || event.clientX > rect.right || event.clientY < rect.top || event.clientY > rect.bottom)) dialog.close();
  });
  dialog.addEventListener('close', () => { document.body.style.overflow = ''; lastDialogTrigger?.focus(); });
});
$('#compare-open').addEventListener('click', event => openDialog($('#compare-dialog'), event.currentTarget));
const finderForm = $('#finder-form');
function showRecommendation() {
  const values = Object.fromEntries(new FormData(finderForm));
  const answered = Object.keys(values).length;
  $('#finder-progress').textContent = `${answered} de 3 respostas`;
  const plan = recommendPlan(values);
  const result = $('#finder-result');
  if (!plan) return;
  result.replaceChildren();
  const label = document.createElement('span');
  label.append('Para o seu perfil, sugerimos ');
  const strong = document.createElement('strong');
  strong.textContent = plan.name;
  label.append(strong, '.');
  const link = document.createElement('a');
  link.href = `#plano-${plan.id}`;
  link.className = 'text-button';
  link.textContent = 'Conhecer plano →';
  result.append(label, link);
}
finderForm.addEventListener('change', showRecommendation);
finderForm.addEventListener('submit', event => { event.preventDefault(); showRecommendation(); });
const coverageForm = $('#coverage-form');
$('#cep').addEventListener('input', event => {
  const value = event.target.value.replace(/\D/g, '').slice(0, 8);
  event.target.value = value.length > 5 ? `${value.slice(0, 5)}-${value.slice(5)}` : value;
});
coverageForm.addEventListener('input', () => { $('#coverage-error').textContent = ''; });
coverageForm.addEventListener('submit', event => {
  event.preventDefault();
  const address = Object.fromEntries(new FormData(coverageForm));
  const error = validateAddress(address);
  $('#coverage-error').textContent = error;
  if (error) return;
  // Same-tab navigation avoids popup blockers and never claims coverage was checked.
  window.location.assign(coverageLink(address));
});
let step = 0;
function updateStep() {
  const current = connectionSteps[step];
  $('#step-count').textContent = `${String(step + 1).padStart(2, '0')} / 05`;
  $('#step-content h4').textContent = current.title;
  $('#step-content p').textContent = current.text;
  $('#step-back').disabled = step === 0;
  const finalStep = step === connectionSteps.length - 1;
  $('#step-next').classList.toggle('hidden', finalStep);
  $('.step-contact').classList.toggle('hidden', !finalStep);
  document.querySelectorAll('.step-track span').forEach((node, i) => node.classList.toggle('active', i <= step));
  if (finalStep) $('.step-contact').focus();
}
$('#step-back').addEventListener('click', () => { step = Math.max(0, step - 1); updateStep(); if (step === 0) $('#step-next').focus(); });
$('#step-next').addEventListener('click', () => { step = Math.min(connectionSteps.length - 1, step + 1); updateStep(); });
const legalContent = {
  privacy: { title: 'Privacidade', paragraphs: [
    'Este website não usa cookies de publicidade ou ferramentas de rastreamento. As respostas do seletor de planos são processadas no seu navegador, sem envio a um servidor.',
    'Na consulta de cobertura, o endereço preenchido é incluído em uma mensagem no WhatsApp. Você decide se deseja enviá-la à Fly. O WhatsApp, a Central do Assinante, as lojas de aplicativos e os testes de velocidade possuem suas próprias políticas de privacidade.',
    'Para obter a política oficial da empresa ou informações sobre o tratamento dos seus dados, solicite atendimento à Fly.'
  ] },
  terms: { title: 'Informações e condições', paragraphs: [
    company.residentialTerms, company.meshTerms,
    'O seletor de planos oferece uma sugestão baseada nas respostas informadas, sem garantir desempenho. A consulta de cobertura é encaminhada ao atendimento e não constitui confirmação de disponibilidade.',
    'A contratação e as condições de prestação do serviço são formalizadas diretamente com a Fly. Solicite o contrato e os termos oficiais antes de contratar.'
  ] },
  lgpd: { title: 'Seus dados pessoais', paragraphs: [
    'Para solicitar informações, acesso, correção ou exclusão de dados pessoais mantidos pela Fly, entre em contato com a equipe e informe a natureza da sua solicitação.',
    'Não envie senhas, documentos ou outros dados sensíveis na mensagem inicial. A equipe deve orientar a identificação e o canal adequado para atender seu pedido.'
  ] },
};
document.querySelectorAll('[data-legal]').forEach(button => button.addEventListener('click', () => {
  const content = legalContent[button.dataset.legal];
  $('#legal-title').textContent = content.title;
  const paragraphs = content.paragraphs.map(text => { const p = document.createElement('p'); p.textContent = text; return p; });
  const contact = document.createElement('a');
  contact.href = whatsapp('Olá! Gostaria de informações sobre privacidade, dados pessoais e documentos oficiais da Fly.');
  contact.target = '_blank'; contact.rel = 'noopener noreferrer'; contact.textContent = 'Solicitar informações à Fly (nova aba)';
  $('#legal-content').replaceChildren(...paragraphs, contact);
  openDialog($('#legal-dialog'), button);
}));
$('#year').textContent = new Date().getFullYear();

})();
