import { mkdir, cp, readFile, writeFile, rm } from 'node:fs/promises';
import { Script } from 'node:vm';
import { render } from '../src/render.js';
import { company } from '../src/data/company.js';

// Keep the editable modules; ship one classic script that also works with file://.
const modules = ['data/company.js', 'data/links.js', 'data/plans.js', 'data/faq.js', 'coverage.js', 'app.js'];
const sources = await Promise.all(modules.map(async file => {
  const source = await readFile(`src/${file}`, 'utf8');
  return `// ${file}\n` + source.replace(/^import .+;\r?\n/gm, '').replace(/^export (?=const |function )/gm, '');
}));
const script = `/* Generated by npm run build. Edit src/ files. */\n(() => {\n'use strict';\n${sources.join('\n\n')}\n})();\n`;
new Script(script, { filename: 'js/main.js' });
const siteUrl = (process.env.SITE_URL || company.domain).replace(/\/$/, '');
if (!/^https?:\/\//.test(siteUrl)) throw new Error('SITE_URL deve ser uma URL HTTP(S).');
await mkdir('js', { recursive: true });
await writeFile('js/main.js', script);
await writeFile('index.html', render({ siteUrl }));
await writeFile('.nojekyll', '');
await writeFile('robots.txt', `User-agent: *\nAllow: /\nSitemap: ${siteUrl}/sitemap.xml\n`);
await writeFile('sitemap.xml', `<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"><url><loc>${siteUrl.replaceAll('&', '&amp;')}/</loc></url></urlset>`);
// dist is exclusively generated output, never an editing location.
await rm('dist', { recursive: true, force: true });
await mkdir('dist', { recursive: true });
for (const file of ['index.html', 'assets', 'css', 'js', 'robots.txt', 'sitemap.xml', '.nojekyll']) {
  await cp(file, `dist/${file}`, { recursive: true });
}
process.stdout.write('Site atualizado: abra index.html diretamente. Cópia para publicação em dist/.\n');
