import { company } from './data/company.js';
import { links, whatsapp } from './data/links.js';
import { plans, money, planLink } from './data/plans.js';
import { faq, connectionSteps } from './data/faq.js';
export const escapeHtml = s => String(s).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const e = escapeHtml;
const icons = {
 arrow: '<path d="M5 12h14m-6-6 6 6-6 6"/>', diagonal: '<path d="M6 18 18 6M6 6h12v12"/>',
 wifi: '<path d="M3 8a15 15 0 0 1 18 0M6 12a10 10 0 0 1 12 0m-9 4a5 5 0 0 1 6 0"/><circle cx="12" cy="20" r="1"/>',
 pin: '<path d="M20 10c0 6-8 12-8 12S4 16 4 10a8 8 0 1 1 16 0Z"/><circle cx="12" cy="10" r="2.5"/>',
 check: '<path d="m5 12 4 4L19 6"/>', plus: '<path d="M12 5v14M5 12h14"/>',
 chat: '<path d="M21 11.5a9 9 0 0 1-13 8L3 21l1.5-5A9 9 0 1 1 21 11.5Z"/><path d="M8 8c0 4 4 8 8 8l1-3-3-1-1 1-2-2 1-1-1-3Z"/>',
 headset: '<path d="M4 14v-3a8 8 0 0 1 16 0v3M4 12h3v7H4a2 2 0 0 1-2-2v-3a2 2 0 0 1 2-2Zm16 0h-3v7h3a2 2 0 0 0 2-2v-3a2 2 0 0 0-2-2Zm0 7c0 3-4 3-7 3"/>',
 bill: '<path d="M6 3h12v18l-3-2-3 2-3-2-3 2ZM9 8h6m-6 4h6"/>', person: '<circle cx="12" cy="8" r="4"/><path d="M4 21v-2a8 8 0 0 1 16 0v2"/>',
 speed: '<path d="M3 19a10 10 0 1 1 18 0H3Zm9-5 5-5"/><circle cx="12" cy="14" r="1"/>', tools: '<path d="m14 6 4 4 3-3a6 6 0 0 1-8 7l-7 7-3-3 7-7a6 6 0 0 1 7-8Z"/>',
 building: '<path d="M4 21V5h10v16M14 10h6v11M2 21h20M8 9h2m-2 4h2m-2 4h2m8-3h1m-1 3h1"/>', shield: '<path d="m12 3 8 3v6c0 5-8 9-8 9s-8-4-8-9V6Z"/><path d="m8 12 3 3 5-6"/>',
};
const icon = (name, cls='') => `<svg class="icon ${cls}" width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${icons[name] || icons.arrow}</svg>`;
const ext = (url, label, cls='') => `<a class="${cls}" href="${e(url)}" target="_blank" rel="noopener noreferrer">${label}<span class="sr-only"> (abre em nova aba)</span></a>`;
const wa = (label, message, cls='button primary') => ext(whatsapp(message), `${label}${icon('diagonal')}`, cls);
const eyebrow = (n, label) => `<div class="eyebrow"><span>${n}</span> ${label}</div>`;
const logo = `<img src="./assets/logo.png" width="1024" height="682" alt="Fly Telecom Fibra" class="logo">`;
function fiberArt(){
 return `<div class="fiber-art" role="img" aria-label="Linhas de fibra óptica formando uma conexão em movimento"><div class="art-coordinate">GRAVATÁ, PE <span>08°12′ S · 35°34′ O</span></div><svg class="fiber-svg" viewBox="0 0 670 620" fill="none" aria-hidden="true"><defs><linearGradient id="fiber" x1="80" y1="620" x2="530" y2="30" gradientUnits="userSpaceOnUse"><stop stop-color="#0752be" stop-opacity="0"/><stop offset=".3" stop-color="#0865eb"/><stop offset=".64" stop-color="#40c8f5"/><stop offset=".85" stop-color="#0787ed"/><stop offset="1" stop-color="#0074eb" stop-opacity="0"/></linearGradient></defs>${Array.from({length:23},(_,i)=>`<path class="fiber-strand" d="M ${-70+i*10} 650 C ${-50+i*12} ${290-i*2}, ${610+i*4} ${520-i*7}, ${513+i*4} ${243-i*3} C ${460+i*4} ${74-i*2}, ${150+i*7} ${325-i*4}, ${425+i*8} -80" stroke="url(#fiber)" stroke-width="${i%6===0?2:0.8}" opacity="${.3+(i%5)*.14}"/>`).join('')}<path class="fiber-pulse" d="M70 650C60 250 675 418 569 201S320 260 537-80" stroke="#acfbff" stroke-width="2" stroke-dasharray="80 1500"/></svg><div class="gig-label"><span class="signal-label"><i></i> SUA VIDA, SEM PAUSA</span><div><strong>${plans[3].speed}</strong><span>${plans[3].unit.toUpperCase()}<small>de possibilidades.</small></span></div><span class="gig-foot">100% fibra. 100% Fly.</span></div><div class="fiber-end"><span class="tiny-node"></span> Uma conexão que vai além. ${icon('diagonal')}</div></div>`;
}
function planCard(p){
 const [integer,cents] = money(p.price).split(',');
 return `<article id="plano-${p.id}" class="plan ${p.featured?'featured':''} ${p.id==='black'?'black':''}"><div class="plan-tag">${p.featured?'NOSSA SUGESTÃO':p.id==='black'?'EXPERIÊNCIA COMPLETA':'100% FIBRA ÓPTICA'}</div><h3>${p.name}</h3><div class="plan-speed">${p.speed}<span>${p.unit}</span></div><p class="plan-caption">${p.caption}</p><ul class="benefits">${p.benefits.map(b=>`<li>${icon('check')}${b}</li>`).join('')}</ul><div class="plan-partners"><img src="./assets/watch.svg" width="60" height="22" alt="Watch" loading="lazy"><span>+</span><img src="./assets/zapping.png" width="70" height="24" alt="Zapping" loading="lazy"></div><div class="price"><span>R$</span><strong>${integer}</strong><b>,${cents}<small>/mês</small></b></div>${ext(planLink(p),`Quero este plano ${icon('diagonal')}`,'button '+(p.featured?'primary':'plan-button'))}</article>`;
}
export function render({ siteUrl = company.domain } = {}){return `<!doctype html>
<html lang="pt-BR"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="theme-color" content="#06111d"><title>Fly Telecom Fibra | Internet fibra óptica em Gravatá</title><meta name="description" content="Conecte sua casa ou empresa em Gravatá com a Fly Telecom Fibra. Conheça os planos, consulte cobertura e tenha atendimento local."><link rel="canonical" href="${e(siteUrl)}/"><meta property="og:type" content="website"><meta property="og:locale" content="pt_BR"><meta property="og:title" content="Fly Telecom Fibra — Gravatá em outra velocidade."><meta property="og:description" content="Internet 100% fibra, Casa Conectada e atendimento pertinho de você. Conheça os planos da Fly."><meta property="og:url" content="${e(siteUrl)}/"><meta property="og:image" content="${e(siteUrl)}/assets/logo.png"><meta property="og:image:alt" content="Fly Telecom Fibra"><meta name="twitter:card" content="summary"><meta name="twitter:title" content="Fly Telecom Fibra | Gravatá conectada"><meta name="twitter:description" content="Internet fibra para sua casa e empresa em Gravatá."><meta name="twitter:image" content="${e(siteUrl)}/assets/logo.png"><link rel="icon" href="./assets/favicon.png"><link rel="preload" href="./assets/manrope-latin.woff2" as="font" type="font/woff2" crossorigin><link rel="stylesheet" href="./css/style.css"><script defer src="./js/main.js"></script><script type="application/ld+json">${JSON.stringify({'@context':'https://schema.org','@type':'LocalBusiness',name:company.name,url:siteUrl,telephone:company.phoneRaw,image:siteUrl+'/assets/logo.png',address:{'@type':'PostalAddress',streetAddress:company.street+', '+company.district,addressLocality:company.city,addressRegion:company.state,addressCountry:'BR'},sameAs:[links.instagram],areaServed:{'@type':'City',name:'Gravatá'}})}</script></head>
<body><a class="skip-link" href="#main">Pular para o conteúdo</a>
<header class="header" id="header"><div class="container header-inner"><a href="#inicio" class="brand" aria-label="Fly Telecom Fibra — início">${logo}</a><button class="menu-toggle" aria-label="Abrir menu" aria-expanded="false" aria-controls="navigation"><span></span><span></span></button><nav id="navigation" aria-label="Navegação principal"><a href="#inicio">Início</a><a href="#planos">Planos</a><a href="#casa-conectada">Casa Conectada</a><a href="#empresas">Empresas</a><a href="#suporte">Suporte</a><a href="#sobre">Sobre a Fly</a><div class="header-actions">${ext(links.central,`${icon('person')} Central do Assinante`,'central-link')}${wa('Assine agora','Olá! Quero contratar a Fly Telecom Fibra.','button primary small')}</div></nav></div></header>
<main id="main"><section class="hero" id="inicio"><div class="container hero-grid"><div class="hero-content"><div class="location-badge"><span class="status-dot"></span>100% FIBRA ÓPTICA <span class="badge-divider"></span> GRAVATÁ — PE</div><h1>Gravatá conectada<br>em outra<br><em>velocidade.</em></h1><p>O mundo não para. Sua conexão também não.<br class="desktop-break"> Fibra óptica e atendimento de verdade, pertinho de você.</p><div class="hero-buttons"><a href="#planos" class="button primary">Encontre seu plano ${icon('arrow')}</a><a href="#cobertura" class="button outline">${icon('pin')} Consultar cobertura</a></div><a href="${links.central}" class="hero-client" target="_blank" rel="noopener noreferrer">Já é de casa? <strong>Acesse a Central do Assinante ${icon('diagonal')}</strong></a></div>${fiberArt()}</div><div class="container hero-bottom"><span>DA NOSSA CIDADE. PARA O SEU MUNDO.</span><a href="#planos">Explore a conexão ${icon('arrow')}</a></div></section>
<div class="trust-strip"><div class="container">${[['wifi','100% fibra óptica'],['headset','Suporte local'],['speed','Wi-Fi de alta performance'],['tools','Instalação rápida'],['shield','Equipe própria']].map(([i,t])=>`<span>${icon(i)}${t}</span>`).join('')}</div></div>
<section id="planos" class="section plans-section"><div class="container"><div class="section-heading reveal"><div>${eyebrow('01','SEU PRÓXIMO PLANO')}<h2>Mais velocidade.<br><span>Mais possibilidades.</span></h2></div><div class="heading-aside"><p>Do primeiro play ao último compromisso.<br>Tem uma Fly para o seu ritmo.</p><button class="text-button" id="compare-open">Comparar planos ${icon('plus')}</button></div></div><div class="plans-grid reveal">${plans.map(planCard).join('')}</div><p class="fine-print">${company.residentialTerms}</p>
<div class="plan-finder reveal" id="seletor"><div class="finder-intro"><span class="mini-label">NA DÚVIDA?</span><h3>Qual Fly combina<br>com sua casa?</h3><p>Conte um pouquinho da sua rotina.<br>A gente ajuda na escolha.</p><span class="finder-progress" id="finder-progress">0 de 3 respostas</span></div><form id="finder-form"><div class="finder-fields">${[['people','Quantas pessoas usam?',['1–2','3–4','5+']],['usage','Qual é o principal uso?',['Streaming','Jogos','Home office','Redes sociais','Tudo isso']],['devices','Quantos dispositivos?',['Até 5','6–10','10+']]].map(([name,label,opts])=>`<fieldset><legend>${label}</legend><div class="choice-group">${opts.map(v=>`<label><input type="radio" name="${name}" value="${v}" required><span>${v}</span></label>`).join('')}</div></fieldset>`).join('')}</div><div class="finder-result" id="finder-result" aria-live="polite"><span>Seu próximo plano começa com a sua rotina.</span><button class="text-button" type="submit">Ver minha sugestão ${icon('arrow')}</button></div><p class="fine-print">Sugestão de perfil, sem medição técnica. Confirme a escolha com nossa equipe.</p></form></div></div></section>
<section class="stream-section"><div class="container stream-inner reveal"><div>${eyebrow('PLAY','TAMBÉM FAZ PARTE')}<h2>Internet para conectar.<br><span>Conteúdo para aproveitar.</span></h2><p>Filmes, séries e canais ao vivo para a sua próxima pausa.</p></div><div class="stream-partners"><div><img src="./assets/watch.svg" alt="Watch" width="130" height="48" loading="lazy"><span>Filmes, séries e conteúdo infantil</span></div><span class="partner-plus">+</span><div><img src="./assets/zapping.png" alt="Zapping" width="145" height="50" loading="lazy"><span>Seus canais em um app</span></div><p>Consulte o catálogo e as condições de acesso do seu plano.</p></div></div></section>
<section class="section home-section" id="casa-conectada"><div class="container split"><div class="home-copy reveal">${eyebrow('02','CASA CONECTADA')}<h2>O Wi-Fi precisa<br>chegar <span>onde<br>você está.</span></h2><p>Da reunião na sala ao filme no quarto. Uma rede pensada para os espaços e a rotina da sua casa.</p><div class="feature-lines"><div><span>01</span><div><h3>Wi-Fi 6 + rede Mesh</h3><p>Tecnologia para distribuir melhor a conexão.</p></div></div><div><span>02</span><div><h3>Cada ponto faz diferença</h3><p>Posicionamento estratégico para reduzir áreas com sinal ruim.</p></div></div><div><span>03</span><div><h3>Sua casa, bem conectada</h3><p>Possibilidade de um ponto adicional, conforme análise técnica.</p></div></div></div>${wa('Conheça a Casa Conectada','Olá! Quero saber mais sobre a Casa Conectada.','button dark')}<p class="fine-print">${company.meshTerms}</p></div><div class="house-visual reveal"><div class="diagram-top"><span>UMA REDE. A CASA TODA.</span>${icon('wifi')}</div><svg viewBox="0 0 520 440" role="img" aria-label="Planta ilustrativa de uma casa com pontos de Wi-Fi na sala e no quarto"><defs><pattern id="house-grid" width="24" height="24" patternUnits="userSpaceOnUse"><path d="M24 0H0V24" fill="none" stroke="#ccd9e1" stroke-width=".5"/></pattern></defs><rect x="20" y="20" width="480" height="400" fill="url(#house-grid)"/><g fill="#f7fafc" stroke="#6c8494" stroke-width="3"><path d="M70 75H450V355H305M255 355H70Z"/><path d="M280 75V190m0 50v115M70 230h115m45 0h50M280 230h65m50 0h55"/></g><g fill="none" stroke="#b8c8d2" stroke-width="2"><rect x="95" y="106" width="54" height="95" rx="5"/><path d="M108 107v94M94 120h55m-55 68h55"/><rect x="175" y="120" width="55" height="60" rx="5"/><rect x="310" y="97" width="105" height="90" rx="4"/><path d="M310 124h105m-52-27v27"/><rect x="104" y="270" width="91" height="48" rx="5"/><path d="M100 283h-13m13 20H87m111-20h14m-14 20h14"/><path d="M320 259h98v66h-98Z"/></g><path d="M211 198 364 203" stroke="#0589e9" stroke-width="2" stroke-dasharray="5 6"/><g class="wifi-waves" fill="none" stroke="#078bf0"><circle cx="211" cy="198" r="45" opacity=".2"/><circle cx="211" cy="198" r="70" opacity=".12"/><circle cx="364" cy="203" r="45" opacity=".2"/><circle cx="364" cy="203" r="70" opacity=".12"/></g><g fill="#087fe8" stroke="white" stroke-width="4"><circle cx="211" cy="198" r="12"/><circle cx="364" cy="203" r="12"/></g><g fill="#496273" font-family="Arial,sans-serif" font-size="14" letter-spacing="1"><text x="176" y="96">SALA</text><text x="331" y="342">ESCRITÓRIO</text><text x="107" y="342">COZINHA</text><text x="324" y="218">QUARTO</text></g></svg><div class="diagram-bottom"><span><i></i> Pontos que conectam</span><span>Wi-Fi 6 / Mesh</span></div><p class="fine-print">Representação ilustrativa. A distribuição depende do imóvel.</p></div></div></section>
<section class="local-section" id="sobre"><div class="container local-grid reveal"><div class="local-title">${eyebrow('03','FEITA DAQUI')}<h2>A internet de<br><span>Gravatá</span><br>conhece Gravatá.</h2><div class="local-location">${icon('pin')} PERNAMBUCO, BRASIL</div></div><div class="local-copy"><span class="mini-label">UMA CONEXÃO MAIS PRÓXIMA.</span><h3>Antes de conectar dispositivos,<br>a gente conecta pessoas.</h3><p>Somos parte da cidade. Nossa equipe está aqui, investindo em tecnologia e cuidando de cada conexão com atendimento local e humano.</p><p>É a tranquilidade de falar com quem está perto. E a liberdade de ir longe.</p><div class="address">${icon('pin')}<div><strong>Venha conversar com a gente.</strong><p>${company.street}<br>${company.district} · ${company.city}, Pernambuco</p></div></div>${ext(links.instagram,'Acompanhe a Fly no Instagram '+icon('diagonal'),'text-link')}</div></div></section>
<section class="coverage-section" id="cobertura"><div class="container coverage-grid reveal"><div>${eyebrow('VAMOS CONECTAR','CONSULTE A COBERTURA')}<h2>A Fly já chegou<br><span>até você?</span></h2><p>Informe seu endereço. Nossa equipe confirma a disponibilidade pelo WhatsApp.</p></div><form id="coverage-form"><div class="form-row"><div class="field"><label for="cep">CEP</label><input id="cep" name="cep" inputmode="numeric" autocomplete="postal-code" placeholder="00000-000" maxlength="9" pattern="[0-9]{5}-?[0-9]{3}" required></div><div class="field"><label for="number">Número</label><input id="number" name="number" placeholder="123 ou S/N" maxlength="20" required></div></div><div class="field"><label for="street">Rua</label><input id="street" name="street" autocomplete="address-line1" placeholder="Qual é o nome da sua rua?" minlength="3" maxlength="150" required></div><p id="coverage-error" class="form-error" role="alert"></p><button class="button primary" type="submit">Consultar cobertura no WhatsApp ${icon('diagonal')}</button><p class="fine-print">Ao continuar, você será direcionado ao WhatsApp para enviar o endereço à Fly. A disponibilidade será confirmada pela equipe.</p></form></div></section>
<section class="section app-section"><div class="container split app-grid"><div class="app-visual reveal"><span class="app-backdrop-word" aria-hidden="true">FLY.</span><img src="./assets/app.png" width="761" height="482" alt="Imagem oficial do aplicativo Fly Telecom com telas de acesso e serviços do assinante" loading="lazy"></div><div class="reveal">${eyebrow('04','A FLY VAI COM VOCÊ')}<h2>Sua conexão.<br><span>Na palma da mão.</span></h2><p>Mais autonomia para cuidar da sua internet.<br>O app Fly deixa tudo mais perto.</p><ul class="app-features">${['Segunda via de faturas','Solicitação de suporte','Desbloqueio em confiança','Serviços do assinante'].map(t=>`<li>${icon('check')}${t}</li>`).join('')}</ul><div class="store-links">${ext(links.apple,'<span>Baixe na</span><strong>App Store</strong>','store-link')}${ext(links.google,'<span>Disponível no</span><strong>Google Play</strong>','store-link')}</div></div></div></section>
<section class="section support-section" id="suporte"><div class="container"><div class="section-heading reveal"><div>${eyebrow('05','JÁ É DE CASA?')}<h2>Resolveu em<br><span>poucos cliques.</span></h2></div><p class="heading-aside">O que você precisa, sem dar voltas.<br>Conte com a gente.</p></div><div class="support-grid reveal">${[['bill','Segunda via',links.central],['headset','Suporte técnico',whatsapp('Olá! Preciso de suporte técnico para minha conexão Fly.')],['person','Central do Assinante',links.central],['speed','Teste de velocidade','#teste'],['tools','Visita técnica',whatsapp('Olá! Gostaria de solicitar uma visita técnica.')],['chat','WhatsApp',whatsapp()]].map(([i,t,l])=>l.startsWith('#')?`<a class="support-link" href="${l}">${icon(i)}<span>${t}</span>${icon('diagonal')}</a>`:ext(l,`${icon(i)}<span>${t}</span>${icon('diagonal')}`,'support-link')).join('')}</div><div class="support-tools"><div class="connection-helper"><div class="helper-header"><h3>Está sem conexão?</h3><span id="step-count">01 / 05</span></div><div class="step-track" aria-hidden="true">${connectionSteps.map((_,i)=>`<span class="${i===0?'active':''}"></span>`).join('')}</div><div id="step-content" aria-live="polite"><h4>${connectionSteps[0].title}</h4><p>${connectionSteps[0].text}</p></div><div class="step-controls"><button class="text-button" id="step-back" disabled>Voltar</button><button class="text-button" id="step-next">Próximo passo ${icon('arrow')}</button>${wa('Falar com suporte','Olá! Já verifiquei os cabos, reiniciei o equipamento e continuo sem conexão.','text-link step-contact hidden')}</div></div><div class="speed-tools" id="teste"><span class="mini-label">COMO ESTÁ SUA INTERNET?</span><h3>Teste sua conexão.</h3><p>Para um resultado mais consistente, prefira um computador conectado por cabo e pause outros downloads.</p><div>${[['Speedtest',links.speedtest],['Minha Conexão',links.connection],['nPerf',links.nperf]].map(([t,l])=>ext(l,t+icon('diagonal'),'text-link')).join('')}</div><span class="fine-print">Os testes são realizados em serviços externos.</span></div></div></div></section>
<section class="business-section" id="empresas"><div class="container business-grid reveal"><div>${eyebrow('FLY EMPRESAS','CONEXÃO QUE TRABALHA COM VOCÊ')}<h2>Seu negócio<br>não pode <span>parar.</span></h2><p>Da pequena empresa à operação que exige mais. Conectividade pensada para o ritmo do seu negócio.</p>${wa('Falar com especialista','Olá! Quero conhecer as soluções empresariais da Fly.','button primary')}</div><div class="business-features">${[['building','Fibra empresarial','Velocidade simétrica para o trabalho fluir.'],['shield','Soluções sob medida','Internet dedicada, SLA e IP fixo sob consulta.'],['headset','Atendimento prioritário','Equipe local e monitoramento para sua operação.']].map(([i,t,p])=>`<div>${icon(i)}<div><h3>${t}</h3><p>${p}</p></div></div>`).join('')}<p class="fine-print">Serviços e condições conforme a solução contratada. Consulte uma proposta para sua empresa.</p></div></div></section>
<section class="referral-section"><div class="container referral-grid reveal"><div><span class="mini-label">CONEXÃO BOA A GENTE COMPARTILHA</span><h2>Indique. Conecte. <span>Ganhe.</span></h2><p>${company.referral.text}</p>${wa('Quero indicar','Olá! Quero participar da promoção de indicação.','text-link')}<details class="referral-terms"><summary>Confira as condições da promoção</summary><p>${company.referral.terms}</p></details></div><div class="discount"><strong>${company.referral.discount}</strong><span>DE DESCONTO<br>EM UMA MENSALIDADE</span></div></div></section>
<section class="section faq-section" id="faq"><div class="container faq-grid"><div class="reveal">${eyebrow('06','SEM FICAR NA DÚVIDA')}<h2>Respostas<br><span>que conectam.</span></h2><p>Precisa de mais uma mão?<br>Nosso time está por aqui.</p>${wa('Converse com a Fly',undefined,'text-link')}</div><div class="faq-list reveal">${faq.map(([q,a])=>`<details><summary>${q}${icon('plus')}</summary><div><p>${a}</p></div></details>`).join('')}</div></div></section>
<section class="final-cta"><div class="container"><span class="mini-label">SEU PRÓXIMO PASSO COMEÇA AQUI.</span><h2>Pronto para voar<br>mais <em>rápido?</em></h2><div><a href="#cobertura" class="button white">Consultar cobertura ${icon('diagonal')}</a>${wa('Falar no WhatsApp',undefined,'button outline')}</div><span class="cta-signature">GRAVATÁ CONECTADA. COM FLY.</span></div></section></main>
<footer><div class="container"><div class="footer-main"><div class="footer-brand"><a href="#inicio" aria-label="Fly Telecom Fibra — início">${logo}</a><p>Da nossa cidade.<br>Para o seu mundo.</p>${ext(links.instagram,'Instagram '+icon('diagonal'),'text-link')}</div><div><h3>Conecte-se</h3><a href="#planos">Internet residencial</a><a href="#empresas">Internet empresarial</a><a href="#casa-conectada">Casa Conectada</a><a href="#cobertura">Consultar cobertura</a></div><div><h3>Já sou cliente</h3>${ext(links.central,'Central do Assinante')}${ext(links.central,'Segunda via')}<a href="#suporte">Suporte técnico</a><a href="#teste">Teste de velocidade</a>${ext(whatsapp('Olá! Gostaria de avaliar os serviços da Fly.'),'Avalie a Fly')}</div><div><h3>A Fly</h3><a href="#sobre">Sobre a Fly</a>${ext(whatsapp('Olá! Gostaria de saber como enviar meu currículo para trabalhar na Fly.'),'Trabalhe conosco')}<h3 class="footer-contact-title">Fale com a gente</h3><a href="tel:${company.phoneRaw}">${company.phone}</a>${ext(whatsapp(),'WhatsApp')}<p>${company.street}<br>${company.district} · ${company.city} — ${company.state}</p></div></div><div class="footer-bottom"><span>© <span id="year">${new Date().getFullYear()}</span> ${company.name}. Todos os direitos reservados.</span><div><button data-legal="privacy">Privacidade</button><button data-legal="terms">Termos</button><button data-legal="lgpd">LGPD</button></div></div></div></footer>
${ext(whatsapp(),`${icon('chat')}<span>Falar com a Fly</span>`,'floating-whatsapp')}
<dialog id="compare-dialog" class="compare-dialog" aria-labelledby="compare-title"><div class="dialog-header"><div><span class="mini-label">ENCONTRE SUA CONEXÃO</span><h2 id="compare-title">Compare os planos.</h2></div><button class="close-dialog" aria-label="Fechar comparação">×</button></div><div class="comparison-grid">${plans.map(p=>`<article class="compare-plan ${p.featured?'is-featured':''}"><h3>${p.name}</h3><dl>${[['Velocidade',p.speed+' '+p.unit],['Wi-Fi',p.wifi],['Casa Conectada',p.home?'Inclusa':'Não inclusa'],['Streaming',p.streaming],['Atendimento',p.support],['Preço','R$ '+money(p.price)+'/mês']].map(([k,v])=>`<div><dt>${k}</dt><dd>${v}</dd></div>`).join('')}</dl>${ext(planLink(p),'Quero este plano '+icon('diagonal'),'button primary')}</article>`).join('')}</div><p class="fine-print">${company.residentialTerms} ${company.meshTerms}</p></dialog>
<dialog id="legal-dialog" class="legal-dialog" aria-labelledby="legal-title"><div class="dialog-header"><h2 id="legal-title"></h2><button class="close-dialog" aria-label="Fechar informações">×</button></div><div id="legal-content"></div></dialog><noscript><div class="noscript-note">Ative o JavaScript para comparar e receber sugestões de planos. Você pode contratar e consultar cobertura diretamente pelo <a href="${whatsapp()}">WhatsApp da Fly</a>.</div></noscript></body></html>`;}
